#!/usr/bin/env python
"""Cluster extracted CellAgent cell features with Scanpy Leiden."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.tools.clustering import config_from_dict, run_feature_clustering


def load_clustering_config(path: str | Path | None) -> dict[str, Any]:
    if not path:
        return {}
    cfg = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    return cfg


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Leiden clustering on CellAgent feature npz/npy.")
    parser.add_argument("--features", required=True, help="Cell feature .npz or .npy generated by extract_cell_encoder_features.py.")
    parser.add_argument("--config", default="config/config.yaml", help="YAML config path.")
    parser.add_argument("--output-dir", default=None, help="Override clustering.output_dir.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    full_cfg = load_clustering_config(args.config)
    raw_cfg = full_cfg.get("clustering", full_cfg)
    pipeline_cfg = full_cfg.get("pipeline", {})
    output_root = Path(pipeline_cfg["output_root"]) if pipeline_cfg.get("output_root") else None
    output_dir = args.output_dir or (str(output_root / "clustering") if output_root else None)
    cfg = config_from_dict(raw_cfg)
    outputs = run_feature_clustering(args.features, cfg=cfg, output_dir=output_dir)
    print(json.dumps({k: str(v) for k, v in outputs.items()}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
