#!/usr/bin/env python
"""Cluster extracted CellAgent cell features with Scanpy Leiden."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.tools.clustering import config_from_dict, run_feature_clustering, write_obs_cluster_assignments


def load_clustering_config(path: str | Path | None) -> dict[str, Any]:
    if not path:
        return {}
    cfg = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    return cfg


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Leiden clustering on CellAgent feature npz/npy.")
    parser.add_argument("--features", default=None, help="Cell feature .npz or .npy generated by extract_cell_encoder_features.py.")
    parser.add_argument("--preprocessed", default=None, help="CellAgent *_preprocessed.h5ad. Required when clustering.source='obs'.")
    parser.add_argument("--config", default="config/config.yaml", help="YAML config path.")
    parser.add_argument("--output-dir", default=None, help="Override clustering.output_dir.")
    parser.add_argument("--source", choices=["cellagent", "obs"], default=None, help="Override clustering.source.")
    parser.add_argument("--obs-key", default=None, help="Override clustering.obs_key when source='obs'.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    full_cfg = load_clustering_config(args.config)
    raw_cfg = full_cfg.get("clustering", full_cfg)
    pipeline_cfg = full_cfg.get("pipeline", {})
    output_root = Path(pipeline_cfg["output_root"]) if pipeline_cfg.get("output_root") else None
    output_dir = args.output_dir or (str(output_root / "clustering") if output_root else None)
    cfg = config_from_dict(raw_cfg)
    if args.source is not None:
        cfg.source = args.source
    if args.obs_key is not None:
        cfg.obs_key = args.obs_key
    if cfg.source == "obs":
        if not args.preprocessed:
            raise ValueError("--preprocessed is required when clustering.source='obs'.")
        outputs = write_obs_cluster_assignments(args.preprocessed, cfg=cfg, output_dir=output_dir)
    elif cfg.source == "cellagent":
        if not args.features:
            raise ValueError("--features is required when clustering.source='cellagent'.")
        outputs = run_feature_clustering(args.features, cfg=cfg, output_dir=output_dir)
    else:
        raise ValueError(f"Unsupported clustering.source: {cfg.source!r}. Expected 'cellagent' or 'obs'.")
    print(json.dumps({k: str(v) for k, v in outputs.items()}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
